### ISSUE TITLE
[Bug]: 3.6.3 Uncaught Exception "No such file or directory"

### ISSUE THREAD

**Issue by tordenflesk** [StuffAnThings/qbit_manage#302]
### Describe the Bug

After upgrading to 3.6.3 there's an error trying to load a torrent that's no longer in the client.
This was also an issue on 'Develop', so i went back to 'Latest'. Now that 3.6.3 got pushed the error returns.

### Config

```yaml
qbt:
  host: X
  user: X
  pass: X

settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  ignoreTags_OnUpdate:
  - noHL
  - issue
  - cross-seed

  nohardlinks_tag: noHL
directory:
  cross_seed: /DATA01/downloads/watch/qbittorrent
  root_dir: /DATA01/downloads/complete
  recycle_bin: /DATA01/downloads/.RecycleBin
  torrents_dir: /config_QBT/BT_backup
  orphaned_dir: /DATA01/downloads/.orphaned_data
  remote_dir: /DATA01/downloads/complete

cat:
  BHD: /DATA01/downloads/complete/BHD
  BTN: /DATA01/downloads/complete/BTN
  CZ: /DATA01/downloads/complete/CZ
  CZ.cross-seed: /DATA01/downloads/complete/CZ
  EMP: /DATA01/downloads/complete/EMP
  NB: /DATA01/downloads/complete/NB
  RADARR: /DATA01/downloads/complete/RADARR
  RADARR.cross-seed: /DATA01/downloads/complete/RADARR
  SONARR: /DATA01/downloads/complete/SONARR
  SONARR.cross-seed: /DATA01/downloads/complete/SONARR
  TL: /DATA01/downloads/complete/TL
  TL.cross-seed: /DATA01/downloads/complete/TL
  _RR.cross-seed: /DATA01/downloads/complete/RR
  _RR: /DATA01/downloads/complete/RR
  SB: /DATA01/downloads/complete/SB/

  complete: /DATA01/downloads/complete/
tracker:
  hdts-announce:
    tag: _HDT
    max_ratio: 1.1
    max_seeding_time: 13824
  beyond-hd:
    tag: _BHD
    max_ratio: 1.1
    max_seeding_time: 13824
  landof.tv:
    tag: _BTN
    max_ratio: 1.1
    max_seeding_time: 8640
  tleechreload:
    tag: _TL
    max_ratio: 1.1
    max_seeding_time: 13824
  torrentleech:
    tag: _TL
    max_ratio: 1.1
    max_seeding_time: 13824
  superbits:
    tag: _SB
    max_ratio: 1.1
    max_seeding_time: 3744
  sptracker:
    tag: _SB
    max_ratio: 1.1
    max_seeding_time: 3744
  norbits:
    tag: _NB
    max_ratio: 1.1
  cathode-ray:
    tag: _CRT
    max_ratio: 1.1
  tracker.empornium.sx:
    tag: _EMP
    max_ratio: 1.1
  tracker.cinemaz.to:
    tag: _CZ
    max_ratio: 0.91
    max_seeding_time: 28320
  other:
    tag: _PBLC
    max_ratio: 1.1
nohardlinks:
  RADARR:
    cleanup: true
    exclude_tags:
  RADARR.cross-seed:
    cleanup: true
    exclude_tags:
  SONARR:
    cleanup: true
    exclude_tags:
  SONARR.cross-seed:
    cleanup: true
    exclude_tags:
  BTN:
    cleanup: true
    exclude_tags:
  BHD:
    cleanup: true
    exclude_tags:
  NB:
    cleanup: true
    exclude_tags:
  _RR:
    cleanup: false
    max_ratio: -1
    exclude_tags:
  _RR.cross-seed:
    cleanup: false
    max_ratio: -1
    exclude_tags:
recyclebin:
  enabled: false
  empty_after_x_days: 3
  split_by_category: false
  save_torrents: false

orphaned:
  empty_after_x_days: 6
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
  - '**/*.mkv'

bhd:
  apikey: 

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
```

### Logs

https://gist.github.com/tordenflesk/4ad11224551455d77492d44895304a73

### Installation

Docker

### Version Number

3.6.3

### What branch are you on?

master

**Comment by KnifeFed** [comment]
I'm having the same issue while checking for hardlinks right after updating to 3.6.3. So far the execution has stopped with errors for random files in `/appdata` (Unraid):

```
/data/appdata/overseerr/logs/.machinelogs.json
/data/appdata/doublecommander/.config/pulse/071ddf28d8834156ba85b53fee684baa-runtime
/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket
```

So, yeah, it may very well be that there's "No such file or directory" between creating the file list and then searching for it (or however that's done).

I, like @tordenflesk, have my `root_dir` and `remote_dir` set to the same path. It's `/data`) in my case because I'm mounting `/mnt/user` as `/data` due to my having separate shares for different types of downloads and this is the only way for qbit_manage to see all of it.
This also made me realize it's very unnecessary to search the whole `root_dir`/`remote_dir` for hardlinks. It would be nice if those could be lists of dirs instead of a single one.

**Comment by KnifeFed** [comment]
@bobokun I'm still getting the same error:

```
[2023-05-28 21:11:53,142] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket not found. Skipping... |
[2023-05-28 21:11:58,031] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonCookie' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonCookie not found. Skipping... |
[2023-05-28 21:12:33,672] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/binhex-radarr/logs.db-shm' : File /data/appdata/binhex-radarr/logs.db-shm not found. Skipping... |
[2023-05-28 21:12:52,019] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonLock' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonLock not found. Skipping... |
[2023-05-28 21:13:04,005] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/binhex-radarr/logs.db-wal' : File /data/appdata/binhex-radarr/logs.db-wal not found. Skipping... |
```

But now, instead of exiting, it tries to tag _almost_ every torrent as `noHL`, which definitely isn't right.

**Comment by bakerboy448** [comment]
What are your container mounts? That sounds more like a configuration issue that QBm is being pointed at appdata

**Comment by bobokun** [comment]
The warning shows that those files are not found when it's scanning for noHL.

Enabling trace logs will help with identifying why it's tagging the torrent as `noHL`.

To enable trace logs add `--trace` or set env variable `QBT_TRACE` to true

**Comment by KnifeFed** [comment]
Did trace logging break? When enabling it, the only log output is the errors:

```
[2023-05-28 22:19:06,499] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonCookie' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonCookie not found. Skipping... |
[2023-05-28 22:19:44,036] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonLock' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonLock not found. Skipping... |
[2023-05-28 22:19:58,347] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket not found. Skipping... |
```

Here's what I get with debug logging enabled. Perhaps not very helpful.
<details>
<summary>Log:</summary>

```
$ docker run --rm \
         --pull='always' \
         --name='qbitmanage-trace' \
         --net='unraiden-bridge' \
         -v '/mnt/cache/appdata/qbit_manage':'/config':'rw' \
         -v '/mnt/user':'/data':'rw' \
         -e TZ="Europe/Berlin" \
         -e HOST_OS="Unraid" \
         -e PUID='99' \
         -e PGID='100' \
         -e UMASK='002' \
         -e QBT_WIDTH='134' \
         -e QBT_DIVIDER='─' \
         -e QBT_RUN='true' \
         -e QBT_SKIP_CLEANUP='true' \
         -e QBT_TAG_UPDATE='true' \
         -e QBT_TAG_NOHARDLINKS='true' \
         -e QBT_TAG_TRACKER_ERROR='true' \
         -e QBT_REM_UNREGISTERED='true' \
         -e QBT_DEBUG='true' \
         -e QBT_DRY_RUN='true' \
         -e QBT_TRACE='false' \
         'bobokun/qbit_manage'
latest: Pulling from bobokun/qbit_manage
Digest: sha256:ae6de960acac9f77723eff00483d12a7eaa48f1543ae3a15b0a5c5aa02032cb0
Status: Image is up to date for bobokun/qbit_manage:latest

[2023-05-28 22:23:54,746] [<module>:552]              [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 22:23:54,746] [<module>:553]              [INFO]     |                                            _     _ _                                                                                 |
[2023-05-28 22:23:54,746] [<module>:554]              [INFO]     |                                           | |   (_) |                                                                                |
[2023-05-28 22:23:54,746] [<module>:555]              [INFO]     |                                       __ _| |__  _| |_   _ __ ___   __ _ _ __   __ _  __ _  ___                                      |
[2023-05-28 22:23:54,746] [<module>:556]              [INFO]     |                                      / _` | '_ \| | __| | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \                                     |
[2023-05-28 22:23:54,746] [<module>:557]              [INFO]     |                                     | (_| | |_) | | |_  | | | | | | (_| | | | | (_| | (_| |  __/                                     |
[2023-05-28 22:23:54,746] [<module>:558]              [INFO]     |                                      \__, |_.__/|_|\__| |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|                                     |
[2023-05-28 22:23:54,746] [<module>:559]              [INFO]     |                                         | |         ______                            __/ |                                          |
[2023-05-28 22:23:54,746] [<module>:560]              [INFO]     |                                         |_|        |______|                          |___/                                           |
[2023-05-28 22:23:54,746] [<module>:562]              [INFO]     |     Version: 3.6.4 (Docker)                                                                                                          |
[2023-05-28 22:23:54,813] [<module>:571]              [INFO]     |     Platform: Linux-5.19.17-Unraid-x86_64-with-glibc2.28                                                                             |
[2023-05-28 22:23:54,813] [<module>:572]              [DEBUG]    |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 22:23:54,814] [<module>:573]              [DEBUG]    |     --run (QBT_RUN): True                                                                                                            |
[2023-05-28 22:23:54,814] [<module>:574]              [DEBUG]    |     --schedule (QBT_SCHEDULE): 1440                                                                                                  |
[2023-05-28 22:23:54,814] [<module>:575]              [DEBUG]    |     --startup-delay (QBT_STARTUP_DELAY): 0                                                                                           |
[2023-05-28 22:23:54,814] [<module>:576]              [DEBUG]    |     --config-file (QBT_CONFIG): ['config.yml']                                                                                       |
[2023-05-28 22:23:54,814] [<module>:577]              [DEBUG]    |     --log-file (QBT_LOGFILE): qbit_manage.log                                                                                        |
[2023-05-28 22:23:54,814] [<module>:578]              [DEBUG]    |     --cross-seed (QBT_CROSS_SEED): False                                                                                             |
[2023-05-28 22:23:54,814] [<module>:579]              [DEBUG]    |     --recheck (QBT_RECHECK): False                                                                                                   |
[2023-05-28 22:23:54,814] [<module>:580]              [DEBUG]    |     --cat-update (QBT_CAT_UPDATE): False                                                                                             |
[2023-05-28 22:23:54,814] [<module>:581]              [DEBUG]    |     --tag-update (QBT_TAG_UPDATE): True                                                                                              |
[2023-05-28 22:23:54,814] [<module>:582]              [DEBUG]    |     --rem-unregistered (QBT_REM_UNREGISTERED): True                                                                                  |
[2023-05-28 22:23:54,815] [<module>:583]              [DEBUG]    |     --tag-tracker-error (QBT_TAG_TRACKER_ERROR): True                                                                                |
[2023-05-28 22:23:54,815] [<module>:584]              [DEBUG]    |     --rem-orphaned (QBT_REM_ORPHANED): False                                                                                         |
[2023-05-28 22:23:54,815] [<module>:585]              [DEBUG]    |     --tag-nohardlinks (QBT_TAG_NOHARDLINKS): True                                                                                    |
[2023-05-28 22:23:54,815] [<module>:586]              [DEBUG]    |     --skip-cleanup (QBT_SKIP_CLEANUP): True                                                                                          |
[2023-05-28 22:23:54,815] [<module>:587]              [DEBUG]    |     --skip-qb-version-check (QBT_SKIP_QB_VERSION_CHECK): False                                                                       |
[2023-05-28 22:23:54,815] [<module>:588]              [DEBUG]    |     --dry-run (QBT_DRY_RUN): True                                                                                                    |
[2023-05-28 22:23:54,815] [<module>:589]              [DEBUG]    |     --log-level (QBT_LOG_LEVEL): DEBUG                                                                                               |
[2023-05-28 22:23:54,815] [<module>:590]              [DEBUG]    |     --divider (QBT_DIVIDER): ─                                                                                                       |
[2023-05-28 22:23:54,815] [<module>:591]              [DEBUG]    |     --width (QBT_WIDTH): 134                                                                                                         |
[2023-05-28 22:23:54,815] [<module>:592]              [DEBUG]    |     --debug (QBT_DEBUG): True                                                                                                        |
[2023-05-28 22:23:54,815] [<module>:593]              [DEBUG]    |     --trace (QBT_TRACE): False                                                                                                       |
[2023-05-28 22:23:54,815] [<module>:594]              [DEBUG]    |                                                                                                                                      |
[2023-05-28 22:23:54,815] [<module>:597]              [INFO]     |     Run Mode: Script will exit after completion.                                                                                     |
[2023-05-28 22:23:54,816] [start:375]                 [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 22:23:54,816] [start:375]                 [INFO]     |                                                             Starting Run                                                             |
[2023-05-28 22:23:54,816] [start:375]                 [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 22:23:54,816] [__init__:41]               [INFO]     | Locating config...                                                                                                                   |
[2023-05-28 22:23:54,816] [__init__:54]               [INFO]     | Using /config/config.yml as config                                                                                                   |
[2023-05-28 22:23:54,832] [__init__:193]              [INFO]     | Connecting to Apprise...                                                                                                             |
[2023-05-28 22:23:54,837] [__init__:208]              [INFO]     | Apprise Connection Successful                                                                                                        |
[2023-05-28 22:23:54,837] [__init__:240]              [INFO]     | Connecting to BHD API...                                                                                                             |
[2023-05-28 22:23:56,977] [__init__:248]              [INFO]     | BHD Connection Successful                                                                                                            |
[2023-05-28 22:23:56,994] [__init__:464]              [INFO]     | Connecting to Qbittorrent...                                                                                                         |
[2023-05-28 22:23:56,994] [__init__:37]               [DEBUG]    | Host: binhex-qbittorrentvpn:8080, Username: (redacted), Password: (redacted)                                                         |
[2023-05-28 22:23:57,064] [__init__:43]               [DEBUG]    | qBittorrent: v4.5.2                                                                                                                  |
[2023-05-28 22:23:57,066] [__init__:44]               [DEBUG]    | qBittorrent Web API: 2.8.19                                                                                                          |
[2023-05-28 22:23:57,066] [__init__:45]               [DEBUG]    | qbit_manage supported versions: v4.3.0 - v4.5.2                                                                                      |
[2023-05-28 22:23:57,066] [__init__:70]               [INFO]     | Qbt Connection Successful                                                                                                            |
[2023-05-28 22:23:57,066] [__init__:83]               [INFO]     |──────────────────────────────────────────────────────── Getting Torrent List ────────────────────────────────────────────────────────|
[2023-05-28 22:23:57,333] [get_torrent_info:125]      [INFO]     |───────────────────────────────────────────────────────── Checking Settings ──────────────────────────────────────────────────────────|
[2023-05-28 22:23:57,333] [get_torrent_info:130]      [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 22:23:57,333] [get_torrent_info:130]      [INFO]     |                                                    Gathering Torrent Information                                                     |
[2023-05-28 22:23:57,333] [get_torrent_info:130]      [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 22:23:59,429] [tags:18]                   [INFO]     |─────────────────────────────────────────────────────────── Updating Tags ────────────────────────────────────────────────────────────|
[2023-05-28 22:23:59,444] [tags:61]                   [DRYRUN]   | No new torrents to tag.                                                                                                              |
[2023-05-28 22:23:59,444] [__init__:36]               [INFO]     |────────────────────────────── Tagging Torrents with Tracker Errors and Removing Unregistered Torrents ───────────────────────────────|
[2023-05-28 22:23:59,448] [rem_unregistered:139]      [DRYRUN]   | No unregistered torrents found.                                                                                                      |
[2023-05-28 22:23:59,448] [tag_nohardlinks:187]       [INFO]     |───────────────────────────────────────────────── Tagging Torrents with No Hardlinks ─────────────────────────────────────────────────|
[2023-05-28 22:25:29,919] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonLock' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonLock not found. Skipping... |
[2023-05-28 22:26:20,391] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket not found. Skipping... |
[2023-05-28 22:26:55,419] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonCookie' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonCookie not found. Skipping... |
[2023-05-28 22:27:00,219] [add_tag_no_hl:54]          [DRYRUN]   |    Torrent Name: File.Name                                                                                                           |
[2023-05-28 22:27:00,219] [add_tag_no_hl:54]          [DRYRUN]   |       Added Tag: noHL                                                                                                                |
[2023-05-28 22:27:00,219] [add_tag_no_hl:54]          [DRYRUN]   |         Tracker: http://tracker.url                                                                                                  |
[2023-05-28 22:27:00,219] [add_tag_no_hl:54]          [DRYRUN]   |     Share Limit: Max Ratio = 4.0, Max Seed Time = 129600 min                                                                         |

[repeat for 1117 out of 1697 torrents]

[2023-05-28 22:27:15,143] [tag_nohardlinks:326]       [DRYRUN]   | Did not Tag/set share limits for 1117 .torrents.                                                                                     |
[2023-05-28 22:27:15,161] [finished_run:408]          [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 22:27:15,161] [finished_run:408]          [INFO]     |                                                             Finished Run                                                             |
[2023-05-28 22:27:15,161] [finished_run:408]          [INFO]     |                                                     Total Torrents Tagged: 1117                                                      |
[2023-05-28 22:27:15,161] [finished_run:408]          [INFO]     |                                                   Total noHL Torrents Tagged: 1117                                                   |
[2023-05-28 22:27:15,161] [finished_run:408]          [INFO]     |                                                          Run Time: 0:03:20                                                           |
[2023-05-28 22:27:15,161] [finished_run:408]          [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
```
</details>

@bakerboy448 See my first comment for context. It's still working great in 3.6.2.

**Comment by bobokun** [comment]
You're right, trace logging did break. I pushed a fix out in develop. Can you please re-run from that branch?

**Comment by KnifeFed** [comment]
Yeah, it works from develop.

<details>
<summary>Log:</summary>

```
[2023-05-28 23:09:05,470] [<module>:552]              [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 23:09:05,470] [<module>:553]              [INFO]     |                                            _     _ _                                                                                 |
[2023-05-28 23:09:05,470] [<module>:554]              [INFO]     |                                           | |   (_) |                                                                                |
[2023-05-28 23:09:05,470] [<module>:555]              [INFO]     |                                       __ _| |__  _| |_   _ __ ___   __ _ _ __   __ _  __ _  ___                                      |
[2023-05-28 23:09:05,471] [<module>:556]              [INFO]     |                                      / _` | '_ \| | __| | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \                                     |
[2023-05-28 23:09:05,471] [<module>:557]              [INFO]     |                                     | (_| | |_) | | |_  | | | | | | (_| | | | | (_| | (_| |  __/                                     |
[2023-05-28 23:09:05,471] [<module>:558]              [INFO]     |                                      \__, |_.__/|_|\__| |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|                                     |
[2023-05-28 23:09:05,471] [<module>:559]              [INFO]     |                                         | |         ______                            __/ |                                          |
[2023-05-28 23:09:05,471] [<module>:560]              [INFO]     |                                         |_|        |______|                          |___/                                           |
[2023-05-28 23:09:05,471] [<module>:562]              [INFO]     |     Version: 3.6.4-develop1 (Docker)                                                                                                 |
[2023-05-28 23:09:05,713] [<module>:571]              [INFO]     |     Platform: Linux-5.19.17-Unraid-x86_64-with-glibc2.28                                                                             |
[2023-05-28 23:09:05,714] [<module>:572]              [DEBUG]    |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 23:09:05,714] [<module>:573]              [DEBUG]    |     --run (QBT_RUN): True                                                                                                            |
[2023-05-28 23:09:05,714] [<module>:574]              [DEBUG]    |     --schedule (QBT_SCHEDULE): 1440                                                                                                  |
[2023-05-28 23:09:05,714] [<module>:575]              [DEBUG]    |     --startup-delay (QBT_STARTUP_DELAY): 0                                                                                           |
[2023-05-28 23:09:05,714] [<module>:576]              [DEBUG]    |     --config-file (QBT_CONFIG): ['config.yml']                                                                                       |
[2023-05-28 23:09:05,714] [<module>:577]              [DEBUG]    |     --log-file (QBT_LOGFILE): qbit_manage.log                                                                                        |
[2023-05-28 23:09:05,714] [<module>:578]              [DEBUG]    |     --cross-seed (QBT_CROSS_SEED): False                                                                                             |
[2023-05-28 23:09:05,714] [<module>:579]              [DEBUG]    |     --recheck (QBT_RECHECK): False                                                                                                   |
[2023-05-28 23:09:05,714] [<module>:580]              [DEBUG]    |     --cat-update (QBT_CAT_UPDATE): False                                                                                             |
[2023-05-28 23:09:05,715] [<module>:581]              [DEBUG]    |     --tag-update (QBT_TAG_UPDATE): True                                                                                              |
[2023-05-28 23:09:05,715] [<module>:582]              [DEBUG]    |     --rem-unregistered (QBT_REM_UNREGISTERED): True                                                                                  |
[2023-05-28 23:09:05,715] [<module>:583]              [DEBUG]    |     --tag-tracker-error (QBT_TAG_TRACKER_ERROR): True                                                                                |
[2023-05-28 23:09:05,715] [<module>:584]              [DEBUG]    |     --rem-orphaned (QBT_REM_ORPHANED): False                                                                                         |
[2023-05-28 23:09:05,715] [<module>:585]              [DEBUG]    |     --tag-nohardlinks (QBT_TAG_NOHARDLINKS): True                                                                                    |
[2023-05-28 23:09:05,715] [<module>:586]              [DEBUG]    |     --skip-cleanup (QBT_SKIP_CLEANUP): True                                                                                          |
[2023-05-28 23:09:05,715] [<module>:587]              [DEBUG]    |     --skip-qb-version-check (QBT_SKIP_QB_VERSION_CHECK): False                                                                       |
[2023-05-28 23:09:05,715] [<module>:588]              [DEBUG]    |     --dry-run (QBT_DRY_RUN): True                                                                                                    |
[2023-05-28 23:09:05,715] [<module>:589]              [DEBUG]    |     --log-level (QBT_LOG_LEVEL): TRACE                                                                                               |
[2023-05-28 23:09:05,715] [<module>:590]              [DEBUG]    |     --divider (QBT_DIVIDER): ─                                                                                                       |
[2023-05-28 23:09:05,715] [<module>:591]              [DEBUG]    |     --width (QBT_WIDTH): 134                                                                                                         |
[2023-05-28 23:09:05,716] [<module>:592]              [DEBUG]    |     --debug (QBT_DEBUG): False                                                                                                       |
[2023-05-28 23:09:05,716] [<module>:593]              [DEBUG]    |     --trace (QBT_TRACE): True                                                                                                        |
[2023-05-28 23:09:05,716] [<module>:594]              [DEBUG]    |                                                                                                                                      |
[2023-05-28 23:09:05,716] [<module>:597]              [INFO]     |     Run Mode: Script will exit after completion.                                                                                     |
[2023-05-28 23:09:05,716] [start:375]                 [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 23:09:05,716] [start:375]                 [INFO]     |                                                             Starting Run                                                             |
[2023-05-28 23:09:05,716] [start:375]                 [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 23:09:05,716] [__init__:41]               [INFO]     | Locating config...                                                                                                                   |
[2023-05-28 23:09:05,716] [__init__:54]               [INFO]     | Using /config/config.yml as config                                                                                                   |
[2023-05-28 23:09:05,735] [__init__:193]              [INFO]     | Connecting to Apprise...                                                                                                             |
[2023-05-28 23:09:05,741] [__init__:208]              [INFO]     | Apprise Connection Successful                                                                                                        |
[2023-05-28 23:09:05,741] [__init__:240]              [INFO]     | Connecting to BHD API...                                                                                                             |
[2023-05-28 23:09:05,741] [search:25]                 [TRACE]    | https://beyond-hd.me/api/torrents/(redacted)                                                                                         |
[2023-05-28 23:09:05,741] [search:26]                 [TRACE]    | JSON: {'search': 'test', 'action': 'search'}                                                                                         |
[2023-05-28 23:09:07,392] [search:29]                 [TRACE]    | <Response [200]>                                                                                                                     |
[2023-05-28 23:09:07,393] [__init__:248]              [INFO]     | BHD Connection Successful                                                                                                            |
[2023-05-28 23:09:07,405] [__init__:464]              [INFO]     | Connecting to Qbittorrent...                                                                                                         |
[2023-05-28 23:09:07,406] [__init__:37]               [DEBUG]    | Host: binhex-qbittorrentvpn:8080, Username: (redacted), Password: (redacted)                                                         |
[2023-05-28 23:09:07,477] [__init__:43]               [DEBUG]    | qBittorrent: v4.5.2                                                                                                                  |
[2023-05-28 23:09:07,478] [__init__:44]               [DEBUG]    | qBittorrent Web API: 2.8.19                                                                                                          |
[2023-05-28 23:09:07,478] [__init__:45]               [DEBUG]    | qbit_manage supported versions: v4.3.0 - v4.5.2                                                                                      |
[2023-05-28 23:09:07,478] [__init__:70]               [INFO]     | Qbt Connection Successful                                                                                                            |
[2023-05-28 23:09:07,479] [__init__:83]               [INFO]     |──────────────────────────────────────────────────────── Getting Torrent List ────────────────────────────────────────────────────────|
[2023-05-28 23:09:07,752] [get_torrent_info:125]      [INFO]     |───────────────────────────────────────────────────────── Checking Settings ──────────────────────────────────────────────────────────|
[2023-05-28 23:09:07,753] [get_torrent_info:130]      [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 23:09:07,753] [get_torrent_info:130]      [INFO]     |                                                    Gathering Torrent Information                                                     |
[2023-05-28 23:09:07,753] [get_torrent_info:130]      [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 23:09:09,562] [tags:18]                   [INFO]     |─────────────────────────────────────────────────────────── Updating Tags ────────────────────────────────────────────────────────────|
[2023-05-28 23:09:09,575] [tags:61]                   [DRYRUN]   | No new torrents to tag.                                                                                                              |
[2023-05-28 23:09:09,575] [__init__:36]               [INFO]     |────────────────────────────── Tagging Torrents with Tracker Errors and Removing Unregistered Torrents ───────────────────────────────|
[2023-05-28 23:09:09,580] [rem_unregistered:139]      [DRYRUN]   | No unregistered torrents found.                                                                                                      |
[2023-05-28 23:09:09,580] [tag_nohardlinks:187]       [INFO]     |───────────────────────────────────────────────── Tagging Torrents with No Hardlinks ─────────────────────────────────────────────────|
[2023-05-28 23:11:05,171] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonCookie' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonCookie not found. Skipping... |
[2023-05-28 23:11:37,561] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonSocket not found. Skipping... |
[2023-05-28 23:11:46,715] [get_inode_count:407]       [WARNING]  | [Errno 2] No such file or directory: '/data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonLock' : File /data/appdata/P3R-Brave-Browser/xdg/config/BraveSoftware/Brave-Browser/SingletonLock not found. Skipping... |
[2023-05-28 23:12:07,697] [nohardlink:432]            [TRACE]    | Checking file: /data/movies/dl/Torrent.Name/Torrent.Name.mkv |
[2023-05-28 23:12:07,697] [nohardlink:433]            [TRACE]    | Checking file inum: 648799829907997745                                                                                               |
[2023-05-28 23:12:07,698] [nohardlink:434]            [TRACE]    | Checking no of hard links: 2                                                                                                         |
[2023-05-28 23:12:07,698] [nohardlink:435]            [TRACE]    | Checking inode_count dict: 2                                                                                                         |
[2023-05-28 23:12:07,700] [tag_nohardlinks:220]       [TRACE]    | tracker["min_seeding_time"] is 0                                                                                                     |
[2023-05-28 23:12:07,700] [tag_nohardlinks:221]       [TRACE]    | nohardlinks[category]["min_seeding_time"] is 43200                                                                                   |
[2023-05-28 23:12:07,700] [tag_nohardlinks:228]       [TRACE]    | Using nohardlinks[category]["min_seeding_time"] 43200                                                                                |
[2023-05-28 23:12:07,700] [tag_nohardlinks:243]       [TRACE]    | tracker["max_ratio"] is None                                                                                                         |
[2023-05-28 23:12:07,700] [tag_nohardlinks:244]       [TRACE]    | nohardlinks[category]["max_ratio"] is 4.0                                                                                            |
[2023-05-28 23:12:07,701] [tag_nohardlinks:254]       [TRACE]    | Using (nohardlinks[category]["max_ratio"]) 4.0                                                                                       |
[2023-05-28 23:12:07,701] [tag_nohardlinks:266]       [TRACE]    | tracker["max_seeding_time"] is None                                                                                                  |
[2023-05-28 23:12:07,701] [tag_nohardlinks:267]       [TRACE]    | nohardlinks[category]["max_seeding_time"] is 129600                                                                                  |
[2023-05-28 23:12:07,701] [tag_nohardlinks:277]       [TRACE]    | Using (nohardlinks[category]["max_seeding_time"]) 129600                                                                             |
[2023-05-28 23:12:07,701] [add_tag_no_hl:54]          [DRYRUN]   |    Torrent Name: Torrent.Name                                                                   |
[2023-05-28 23:12:07,701] [add_tag_no_hl:54]          [DRYRUN]   |       Added Tag: noHL                                                                                                                |
[2023-05-28 23:12:07,701] [add_tag_no_hl:54]          [DRYRUN]   |         Tracker: http://tracker.url                                                                                |
[2023-05-28 23:12:07,701] [add_tag_no_hl:54]          [DRYRUN]   |     Share Limit: Max Ratio = 4.0, Max Seed Time = 129600 min                                                                         |
[2023-05-28 23:12:07,701] [_request:62]               [TRACE]    |                                                                                                                                      |
[2023-05-28 23:12:07,701] [_request:63]               [TRACE]    | JSON: {'function': 'tag_nohardlinks', 'title': 'Tagging Torrents with No Hardlinks', 'body': '   Torrent Name: Torrent.Name\n      Added Tag: noHL\n        Tracker: http://tracker.url\n    Share Limit: Max Ratio = 4.0, Max Seed Time = 129600 min', 'torrent_name': 'Torrent.Name', 'torrent_category': 'radarr', 'torrent_tag': 'noHL', 'torrent_tracker': 'http://tracker.url', 'notifiarr_indexer': None, 'torrent_max_ratio': 4.0, 'torrent_max_seeding_time': 129600, 'torrent_limit_upload_speed': 0} |
[2023-05-28 23:12:07,701] [_request:66]               [TRACE]    | Webhook: None

[repeat for 1117 out of 1697 torrents]

[2023-05-28 23:12:24,350] [tag_nohardlinks:326]       [DRYRUN]   | Did not Tag/set share limits for 1117 .torrents.                                                                                     |
[2023-05-28 23:12:24,370] [finished_run:408]          [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
[2023-05-28 23:12:24,370] [finished_run:408]          [INFO]     |                                                             Finished Run                                                             |
[2023-05-28 23:12:24,370] [finished_run:408]          [INFO]     |                                                     Total Torrents Tagged: 1117                                                      |
[2023-05-28 23:12:24,370] [finished_run:408]          [INFO]     |                                                   Total noHL Torrents Tagged: 1117                                                   |
[2023-05-28 23:12:24,370] [finished_run:408]          [INFO]     |                                                          Run Time: 0:03:18                                                           |
[2023-05-28 23:12:24,370] [finished_run:408]          [INFO]     |──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────|
```
</details>

So here it checks `/data/movies/dl/Torrent.Name/Torrent.Name.mkv` and finds 2 hardlinks. The other link is in `/data/movies/lib/Movie Name (2000)/Torrent.Name.mkv`. Does it think it doesn't count because they're both within `/data`?

**Comment by bobokun** [comment]
The new logic of calculating noHL (#291) makes the assumption that your media directory is not in your root folder. Any hardlinks that are found in the root folder are assumed to be associated with qbitorrent's root directory and are considered `noHL` from qbm point of view.

**Comment by KnifeFed** [comment]
That's what I suspected. So how could this work when you have media on multiple shares, e.g. `/mnt/user/movies`, `/mnt/user/tv` etc.? The reason I have separate shares is because of how Unraid's split levels work. 
For movies, I've set it up so that a single movie directory and the directory it's hard-linked from, e.g. `/mnt/user/movies/lib/Movie Name (2023)` and `/mnt/user/movies/dl/Movie.Name.2023…`, are never split across multiple disks.
For TV, I have it so that a single season directory is never split. This requires two different split levels and hence two different shares.
TRaSH's guides are great but they don't account for this Unraid-specific scenario.

@tordenflesk I assume you have the same issue with hardlinks now since you also have `root_dir`/`remote_dir` set the same?

**Comment by tordenflesk** [comment]
I don't use HardLinks at all. The "Ghosts" are still showing up in the log though. No idea where they're being pulled from
```

|====================================================================================================|
|                                            Starting Run                                            |
|====================================================================================================|
| Locating config...                                                                                 |
| Using /config/config.yml as config                                                                 |
| Connecting to BHD API...                                                                           |
| BHD Connection Successful                                                                          |
| Connecting to Qbittorrent...                                                                       |
| Host: 10.0.0.106:8090, Username: (redacted), Password: (redacted)                                  |
| qBittorrent: v4.5.2                                                                                |
| qBittorrent Web API: 2.8.19                                                                        |
| qbit_manage supported versions: v4.3.0 - v4.5.2                                                    |
| Qbt Connection Successful                                                                          |
|======================================= Getting Torrent List =======================================|
|======================================== Checking Settings =========================================|
|====================================================================================================|
|                                   Gathering Torrent Information                                    |
|====================================================================================================|
|======================================= Updating Categories ========================================|
| No new torrents to categorize.                                                                     |
|========================================== Updating Tags ===========================================|
| No new torrents to tag.                                                                            |
|================================== Removing Unregistered Torrents ==================================|
| No unregistered torrents found.                                                                    |
|================================ Tagging Torrents with No Hardlinks ================================|
| [Errno 2] No such file or directory: '/DATA01/downloads/complete/RADARR/Bullet Train (2022) (1080p MA WEB-DL H264 SDR DDP Atmos 5.1 English - HONE).mkv' : File /DATA01/downloads/complete/RADARR/Bullet Train (2022) (1080p MA WEB-DL H264 SDR DDP Atmos 5.1 English - HONE).mkv not found. Skipping... |
| [Errno 2] No such file or directory: '/DATA01/downloads/complete/SONARR/ncis.los.angeles.s14e01.1080p.web.h264-glhf.mkv' : File /DATA01/downloads/complete/SONARR/ncis.los.angeles.s14e01.1080p.web.h264-glhf.mkv not found. Skipping... |
| No torrents found in the category (BTN) defined under nohardlinks attribute in the config. Please check if this matches with any category in qbittorrent and has 1 or more torrents. |
| No torrents found in the category (BHD) defined under nohardlinks attribute in the config. Please check if this matches with any category in qbittorrent and has 1 or more torrents. |
| No torrents found in the category (NB) defined under nohardlinks attribute in the config. Please check if this matches with any category in qbittorrent and has 1 or more torrents. |
| No torrents to tag with no hardlinks.                                                              |
|=================================== Checking for Orphaned Files ====================================|
| Locating orphan files                                                                              |
| Processing orphan exclude patterns                                                                 |
| No Orphaned Files found.                                                                           |
|====================================================================================================|
|                              Emptying Orphaned Data (Files > 6 days)                               |
|====================================================================================================|
|=========================== Searching: /DATA01/downloads/.orphaned_data ============================|
|====================================================================================================|
|                                            Finished Run                                            |
|                                         Run Time: 0:00:04                                          |
|                    Current Time: 23:37 | 30 Minutes until the next run at 00:07                    |
|====================================================================================================|
```

**Comment by bakerboy448** [comment]
There's nothing to fix on qbm's side for a poor user setup and poor configuration that breech the fact that downloads and libraries cannot and should not be mixed

Those files based on their paths seem likely to be coming from your torrent client and generally appears unrelated to this issue at hand.

**Comment by bakerboy448** [comment]
Your easy workaround - and unnecessary asshole commentary aside - would likely be multiple config files if not multiple instances to handle your specific shares in each.

**Comment by KnifeFed** [comment]
> unnecessary asshole commentary

That's insanely ironic coming from you, as that's your whole brand. I see you learned zero humility after the issues with the arrs.

**Comment by bobokun** [comment]
@KnifeFed , the best option like @bakerboy448 mentioned is to separate your qbitorrent instances by your unraid shares so only the torrents referencing your movies share would go into your movies qbitorrent instance. You won't need multiple qbit-manage instances because qbm can read multiple configurations. 

If you don't want to go with this approach you can always fork the current version of qbm and apply a patch to the noHL section so it uses the logic from 3.6.2, but that's up to you to maintain and I can't guarantee future changes won't break

**Comment by KnifeFed** [comment]
Thanks, @bobokun, I appreciate the help.
